### ISSUE TITLE
Correct DB host 

### ISSUE THREAD

**Issue by dyakovlab** [paskal/bitrix.infra#5]
Please specify that you need set DB host 'mysql' in dbconn.php and .settings.php according hostname in docker-compose file 
localhost and 127.0.0.1 will not work
(No such file or directory / Connection refused)

Hope this will help somebody to save couple hours =)

**Comment by paskal** [comment]
It would work as `/var/run/mysqld` is mounted from the `mysql` container to container `php` for faster-than-TCP communications. From `docker-compose.yml`:

```
            # MySQL socket to prevent transferring data through TCP
            # do chown 1001:1001 ./private/mysqld
            - ./private/mysqld:/var/mysql-socket
```

I assume your setup didn't work because you didn't run `chown`. The command was not right before, and I just fixed it.

If you know where you would expect mention of that command? Running `sudo ./scripts/fix-rights.sh` would also fix the access rights for you.

**Comment by paskal** [comment]
Resolving, feel free to reopen if you know a way of improving the code\documentation.
